version: "3.9"

services:
  java_app:
    container_name: java_app
    image: java-app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:mysql://java_db:3306/prueba
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=password
    depends_on:
      java_db:
        condition: service_healthy
  java_db:
    container_name: java_db
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prueba
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
